### ISSUE TITLE
Receiver Jam causes crash

### ISSUE THREAD

**Issue by skarragallagher** [TD22057/ad-mqtt#10]
I have been having some RF interference because of some devices in the house. Ultimately this crashes the script requiring a restart.

Any ideas? 

![image](https://user-images.githubusercontent.com/21247946/188014088-61369f38-1188-4191-9983-e320d8a4694e.png)

2022-09-01 14:04:40.117 ERROR Bridge: Skipping unknown zone 90
2022-09-01 14:04:40.118 ERROR run: Unexpected exception
Traceback (most recent call last):
  File "./ad_mqtt/run.py", line 61, in run
    loop.select()
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/insteon_mqtt/network/poll.py", line 229, in select
    if link.read_from_link() == -1:
  File "./ad_mqtt/Client.py", line 115, in read_from_link
    self.parse_read_buf()
  File "./ad_mqtt/Client.py", line 133, in parse_read_buf
    self.on_read(data=line)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1041, in _on_read
    self._handle_message(data)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 439, in _handle_message
    msg = self._handle_keypad_message(data)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 481, in _handle_keypad_message
    self._update_internal_states(msg)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 632, in _update_internal_states
    self._update_zone_tracker(message)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1017, in _update_zone_tracker
    self._zonetracker.update(message)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 207, in update
    self._add_zone(zone, status=status)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 336, in _add_zone
    self._update_zone(zone, status=status)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 366, in _update_zone
    self.on_fault(zone=zone)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1053, in _on_zone_fault
    self.on_zone_fault(*args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "./ad_mqtt/Bridge.py", line 199, in on_zone_fault
    self.publish(self.sensor_state_topic, {}, payload, zone_num=zone,
  File "./ad_mqtt/Bridge.py", line 140, in publish
    topic_str = topic.format(**topic_args)
KeyError: 'entity'

**Comment by TD22057** [comment]
I pushed an update which will at least catch that error, put it in the logs, and keep going.  So it will basically just log it and ignore it.

I'm leaving this issue open until I/we figure out what the best behavior for this type of message should be.  It's reporting as a zone 90 fault so I could put in special handling for that.  It looks like zones 90 and 91 are configurable according to this: http://site.aesecurity.com/Manuals/v15pand20pprogrammingguide.pdf
Not sure what that translates to in an MQTT topic/message though.  You can always just use the existing system and create a zone 90 config input and that will fault the zone in HASS where you can set up an automation to do something (what I have no idea but at least you'd know about it).

**Comment by skarragallagher** [comment]
I didn't rebuild but i pushed the change on Bridge.py removing line 140 and adding the catch.

`Traceback (most recent call last):
  File "./ad_mqtt/Bridge.py", line 142, in publish
    topic_str = topic.format(**topic_args)
KeyError: 'entity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ad-mqtt/./run.py", line 144, in <module>
    AD.run.run(cfg, alarm_code, devices)
  File "./ad_mqtt/run.py", line 61, in run
    loop.select()
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/insteon_mqtt/network/poll.py", line 229, in select
    if link.read_from_link() == -1:
  File "./ad_mqtt/Client.py", line 115, in read_from_link
    self.parse_read_buf()
  File "./ad_mqtt/Client.py", line 133, in parse_read_buf
    self.on_read(data=line)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1041, in _on_read
    self._handle_message(data)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 439, in _handle_message
    msg = self._handle_keypad_message(data)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 481, in _handle_keypad_message
    self._update_internal_states(msg)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 632, in _update_internal_states
    self._update_zone_tracker(message)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1017, in _update_zone_tracker
    self._zonetracker.update(message)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 207, in update
    self._add_zone(zone, status=status)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 336, in _add_zone
    self._update_zone(zone, status=status)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/zonetracking.py", line 366, in _update_zone
    self.on_fault(zone=zone)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/decoder.py", line 1053, in _on_zone_fault
    self.on_zone_fault(*args, **kwargs)
  File "/root/ad-mqtt/venv/lib/python3.9/site-packages/alarmdecoder/event/event.py", line 84, in fire
    func(self.obj, *args, **kwargs)
  File "./ad_mqtt/Bridge.py", line 207, in on_zone_fault
    self.publish(self.sensor_state_topic, {}, payload, zone_num=zone,
  File "./ad_mqtt/Bridge.py", line 146, in publish
    topic_args, message)
NameError: name 'message' is not defined
`

**Comment by skarragallagher** [comment]
So to get around this i removed the message key in the log update command. It appears something else needs to be updated. At least it won't crash however i think i broke logging efforts. If you can take a look at this at some point I would greatly appreciate it

**Comment by TD22057** [comment]
I fixed the incorrect debug format.  And the bug was caused by a missing return when it hit the unknown zone 90 message.  So I think it should work fine now.
